#!/usr/bin/env python3
"""Generate src/spwm_font.h: a 6x8 bitmap font for ASCII 32..126.

    python tools/make_font.py [--preview]

Rendered from DejaVu Sans Mono, which ships with matplotlib under the Bitstream
Vera licence -- free to use, modify and redistribute, and compatible with this
library's GPL. Do NOT swap in a system font such as Consolas: those are
proprietary and their bitmaps cannot be redistributed in a public repository.

The output is committed, so building the library needs neither Python nor the
font. This script exists so the data is auditable and reproducible rather than
a wall of unexplained hex.
"""

import argparse
import os

import matplotlib
from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 6, 8      # 21 characters across a 128 px panel, 8 lines down
FIRST, LAST = 32, 126

FONT_PATH = os.path.join(os.path.dirname(matplotlib.__file__),
                         "mpl-data", "fonts", "ttf", "DejaVuSansMono.ttf")


def render(px, threshold, dx, baseline):
    """Rasterise the printable ASCII range into CELL_H bytes per glyph.

    Positioned by BASELINE, not by the text box. At px=8 DejaVu Sans Mono has
    ascent 8, descent 2 and cap height 6, so a baseline at row 6 puts capitals
    at row 0 and lets descenders reach row 8 -- exactly the cell. Offsetting by
    the bounding box instead clips descenders and shifts glyphs unpredictably,
    which is what the first attempt at this got wrong.
    """
    font = ImageFont.truetype(FONT_PATH, px)
    ascent, _ = font.getmetrics()
    dy = baseline - ascent
    glyphs = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (CELL_W, CELL_H), 0)
        ImageDraw.Draw(img).text((dx, dy), chr(code), font=font, fill=255)
        rows = []
        for y in range(CELL_H):
            bits = 0
            for x in range(CELL_W):
                if img.getpixel((x, y)) >= threshold:
                    bits |= 1 << x          # bit 0 is the leftmost column
            rows.append(bits)
        glyphs.append(rows)
    return glyphs


def preview(glyphs, sample="ABCgjq0189 %#@"):
    for ch in sample:
        rows = glyphs[ord(ch) - FIRST]
        print("  '%s'" % ch)
        for r in rows:
            print("    " + "".join("#" if r & (1 << x) else "." for x in range(CELL_W)))


def emit(glyphs, path):
    lines = [
        "// spwm_font.h -- 6x8 bitmap font, ASCII 32..126.",
        "//",
        "// GENERATED by tools/make_font.py -- do not edit by hand.",
        "//",
        "// Rasterised from DejaVu Sans Mono (Bitstream Vera licence: free to use,",
        "// modify and redistribute, GPL-compatible). One byte per pixel row, bit 0",
        "// is the leftmost column, so a glyph is CELL_H bytes.",
        "//",
        "// 6x8 fits 21 characters across a 128 px panel and 8 lines down a 64 px one.",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "#define SPWM_FONT_W     %d" % CELL_W,
        "#define SPWM_FONT_H     %d" % CELL_H,
        "#define SPWM_FONT_FIRST %d" % FIRST,
        "#define SPWM_FONT_LAST  %d" % LAST,
        "",
        "static const uint8_t SPWM_FONT[%d][%d] = {" % (len(glyphs), CELL_H),
    ]
    for i, rows in enumerate(glyphs):
        code = FIRST + i
        ch = chr(code)
        label = "space" if ch == " " else ("backslash" if ch == "\\" else ch)
        lines.append("    { %s },  // %3d '%s'"
                     % (", ".join("0x%02X" % r for r in rows), code, label))
    lines += ["};", ""]
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true")
    ap.add_argument("--px", type=int, default=8)
    ap.add_argument("--threshold", type=int, default=100)
    ap.add_argument("--dx", type=float, default=0.0)
    ap.add_argument("--baseline", type=int, default=6)
    a = ap.parse_args()

    g = render(a.px, a.threshold, a.dx, a.baseline)
    if a.preview:
        preview(g)
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "src", "spwm_font.h")
    emit(g, out)
    print("wrote %s  (%d glyphs, %d bytes)"
          % (out, len(g), len(g) * CELL_H))
